// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAAmAUNDchGfTM36q9A9nHU0KU9QLZmaI',
    appId: '1:275411121861:web:09c794bfd788fa8ac7a2ac',
    messagingSenderId: '275411121861',
    projectId: 'benny-lai',
    authDomain: 'benny-lai.firebaseapp.com',
    databaseURL: 'https://benny-lai.firebaseio.com',
    storageBucket: 'benny-lai.appspot.com',
    measurementId: 'G-CFG3ETW3QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcoUNV5tJMy5uPEKaqTdr3UGugtAnX6R4',
    appId: '1:275411121861:android:82d67e9fcca28054c7a2ac',
    messagingSenderId: '275411121861',
    projectId: 'benny-lai',
    databaseURL: 'https://benny-lai.firebaseio.com',
    storageBucket: 'benny-lai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PAl5QrnoKZ5yPuWpENWyiGg-yNaLD9o',
    appId: '1:275411121861:ios:1f08b345ac3b2f85c7a2ac',
    messagingSenderId: '275411121861',
    projectId: 'benny-lai',
    databaseURL: 'https://benny-lai.firebaseio.com',
    storageBucket: 'benny-lai.appspot.com',
    iosClientId: '275411121861-qnk2ioni78bppiaob5t3l249iadllt1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mysite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PAl5QrnoKZ5yPuWpENWyiGg-yNaLD9o',
    appId: '1:275411121861:ios:1f08b345ac3b2f85c7a2ac',
    messagingSenderId: '275411121861',
    projectId: 'benny-lai',
    databaseURL: 'https://benny-lai.firebaseio.com',
    storageBucket: 'benny-lai.appspot.com',
    iosClientId: '275411121861-qnk2ioni78bppiaob5t3l249iadllt1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mysite',
  );
}
